Creacion de Sidebar y enrutamiento
panchocorderos/lesson_link_front pull request #1
Opened 2023-03-16 20:08 UTC by javonunezz

Se creó el sidebar con sus respectivos componentes, se modifico el diseño para que sea responsivo y se configuró el enrutamiento para cada boton presente en el sidebar

2023-03-16 20:15 UTC, yurehn commented on src/components/Sidebar.jsx
> +          {/* <div className="bg-gray-800 w-1/8 space-y-6 py-7 px-2 absolute inset-y-0 md:relative transition duration-200 ease-in-out px-5 top-0 md:bottom-auto"> */}
Eliminar comentario

2023-03-16 20:18 UTC, yurehn commented on src/components/ButtonSidebar.jsx
> +    <button onClick={ handleClick } className="flex items-center justify-center md:justify-start block py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700 text-white bg-gray-800 hover:borde
revisar tailwind [flex, block]

2023-03-16 20:20 UTC, yurehn requested changes
Corregir y revisar puntos señalados 👍

2023-03-16 20:21 UTC, panchocorderos requested changes
Eliminar comentarios redundantes y actualizar la utilización de la libreria react router

2023-03-16 20:21 UTC, panchocorderos commented on src/components/ButtonSidebar.jsx
> +// Component ElementSidebar
Eliminar los comentarios, es redundante esta información

2023-03-16 20:21 UTC, panchocorderos commented on src/components/Sidebar.jsx
> +// Date Created: 09-03-23
Lo mismo que el comentario anterior

2023-03-16 20:21 UTC, panchocorderos commented on src/components/ButtonSidebar.jsx
> +    <button onClick={ handleClick } className="flex items-center justify-center md:justify-start block py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700 text-white bg-gray-800 hover:borde
Utilizar los componentes Link que trae la librería  https://reactrouter.com/en/main/components/link

2023-03-17 19:50 UTC, javonunezz commented on src/components/ButtonSidebar.jsx
> +    <button onClick={ handleClick } className="flex items-center justify-center md:justify-start block py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700 text-white bg-gray-800 hover:borde
corregido el block no estaba siendo tomado en cuenta ya que no pueden haber dos display en el mismo elemento

2023-03-17 19:54 UTC, yurehn approved these changes

2023-03-19 19:20 UTC, panchocorderos approved these changes

2023-03-20 04:07 UTC, merged